dependencies:
- name: aspnet-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: demo80
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: demo81
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: golang-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
- name: node-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: open-liberty
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.0
- name: python-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rails-shopping-cart
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: react-quickstart
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rust-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: spring-boot-http-gradle
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: spring-boot-rest-prometheus
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: spring-boot-watch-pipeline-activity
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.0
- name: test-golang
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: vertx-rest-prometheus
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: voting-app-result-nodejs1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: voting-app-vote-python
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: voting-app-worker-dotnet
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: voting-app-worker-dotnet1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
